import React, { useState, useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import globalSaga from "../stores/globalSaga";
import globalSlice from "../stores/globalSlice";
import { useInjectReducer, useInjectSaga } from "redux-injectors";
import { useDispatch, useSelector } from "react-redux";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [value, setvalue] = useState("");
  const [data, setData] = useState({});

  useInjectSaga({ key: "global", saga: globalSaga });
  useInjectReducer({ key: "global", reducer: globalSlice });
  const dispatch = useDispatch();
  const testData = useSelector((state) => state.global.testData);

  useEffect(() => {
    setData(testData);
  }, [testData]);

  const handleInputChange = (e) => {
    setvalue(e.target.value);
  };
  const handleClick = (e) => {
    if (e.key === "Enter") {
      dispatch({
        type: "SET_TEST_DATA",
        payload: { name: value },
      });
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div style={{ backgroundColor: "gray", padding: 30, borderRadius: 30 }}>
          <h1>Hello, {data.name}</h1>
          <div style={{ marginTop: 20 }}>
            <input
              value={value}
              type="text"
              onChange={handleInputChange}
              placeholder="Enter value"
              onKeyPress={handleClick}
              style={{ width: 500, height: 50, borderRadius: 30, padding: 20 }}
            />
          </div>
        </div>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>src/pages/index.js</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{" "}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>
      </main>
    </>
  );
}
